package com.dreamfactory.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.*;

public class DeviceResponse {
  /* Identifier of this device. */
  @JsonProperty("id")
  private Integer id = null;
  /* Unique ID generated by the device. */
  @JsonProperty("uuid")
  private String uuid = null;
  /* Platform information of the device. */
  @JsonProperty("platform")
  private String platform = null;
  /* Version information of the device. */
  @JsonProperty("version")
  private String version = null;
  /* Model information of the device. */
  @JsonProperty("model")
  private String model = null;
  /* Extra information from the device. */
  @JsonProperty("extra")
  private String extra = null;
  /* Date this device was created. */
  @JsonProperty("created_date")
  private String created_date = null;
  /* Date this device was last modified. */
  @JsonProperty("last_modified_date")
  private String last_modified_date = null;
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  public String getUuid() {
    return uuid;
  }
  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public String getPlatform() {
    return platform;
  }
  public void setPlatform(String platform) {
    this.platform = platform;
  }

  public String getVersion() {
    return version;
  }
  public void setVersion(String version) {
    this.version = version;
  }

  public String getModel() {
    return model;
  }
  public void setModel(String model) {
    this.model = model;
  }

  public String getExtra() {
    return extra;
  }
  public void setExtra(String extra) {
    this.extra = extra;
  }

  public String getCreated_date() {
    return created_date;
  }
  public void setCreated_date(String created_date) {
    this.created_date = created_date;
  }

  public String getLast_modified_date() {
    return last_modified_date;
  }
  public void setLast_modified_date(String last_modified_date) {
    this.last_modified_date = last_modified_date;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceResponse {\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  uuid: ").append(uuid).append("\n");
    sb.append("  platform: ").append(platform).append("\n");
    sb.append("  version: ").append(version).append("\n");
    sb.append("  model: ").append(model).append("\n");
    sb.append("  extra: ").append(extra).append("\n");
    sb.append("  created_date: ").append(created_date).append("\n");
    sb.append("  last_modified_date: ").append(last_modified_date).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

